---

name: face_alignment

gops: [39.285107688]

shapes:
  - [1, 3, 112, 112]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/face_alignment.onnx
    --input_shapes [[1,3,112,112]]
    --resize_dims 256,256
    --mean 123.675,116.28,103.53
    --scale 0.01712475,0.01750700,0.01742919
    --test_input $(root)/dataset/samples/cat.jpg
    --test_result $(name)_top_outputs.npz
    --pixel_format rgb
    --mlir $(workdir)/transformed.mlir

mlir_calibration:
  run_calibration.py $(workdir)/transformed.mlir
    --dataset $(imagenet2012_mlir_cali_set)
    --input_num 100
    -o $(home)/cali_table

BM1684X:
  deploy:
    - model_deploy.py  --mlir $(workdir)/transformed.mlir
        --quantize F32
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.90,0.90
        --model $(workdir)/$(name)_bm1684x_f32.bmodel
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize INT8
        --calibration_table $(home)/cali_table
        --quant_input
        --quant_output
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.85,0.45
        --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize INT8
        --asymmetric
        --calibration_table $(home)/cali_table
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.90,0.55
        --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel