---

name: PP-OCRv3rec
gops: 1.347
shapes:
  - [1, 3, 48, 320]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/ch_PP-OCRv3_rec_infer.onnx
    --test_input $(root)/dataset/samples/ocr_img.jpg
    --input_shapes [$(shape_param)]
    --keep_aspect_ratio
    --pixel_format bgr
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

# mlir_calibration:
#   run_calibration.py $(workdir)/transformed.mlir
#     --dataset $(coco2017_mlir_cali_set)
#     --input_num 100
#     -o $(workdir)/$(name).calitable

BM1684X:
  deploy:
    - model_deploy.py  --mlir $(workdir)/transformed.mlir
        --quantize F32
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_bm1684x_f32.bmodel
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize F16
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.95,0.85
        --model $(workdir)/$(name)_bm1684x_f16.bmodel
