---

name: mobilebert-tflite
gops: [19.269994752]
shapes:
  - [[1, 384], [1, 384], [1, 384]]


mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/lite-model_mobilebert_int8_1.tflite
    --test_input $(root)/dataset/npz_input/squad_data.npz
    --input_shapes [$(shape_param)]
    --model_format=nlp
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir


deploy:
  - model_deploy.py  --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --asymmetric
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel
