---

name: resneXt50-v1

gops: [7.894, 15.788]

shapes:
  - [1, 3, 224, 224]
  - [4, 3, 224, 224]

precision: true

model: $(home)/resnext50_32x4d_v1_dyn.onnx

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(model)
    --input_shapes [$(shape_param)]
    --mean 103.53,116.28,123.675
    --scale 0.0174291938,0.0175070028,0.0171247538
    --pixel_format rgb
    --test_input $(root)/dataset/samples/dog.jpg
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/$(name).mlir

mlir_calibration:
  run_calibration.py $(workdir)/$(name).mlir
    --dataset $(imagenet2012_mlir_cali_set)
    --input_num 100
    -o $(workdir)/$(name)_cali_table

deploy:
  - model_deploy.py  --mlir $(workdir)/$(name).mlir
      --quantize F32
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_$(target)_f32.bmodel
  - model_deploy.py --mlir $(workdir)/$(name).mlir
      --quantize INT8
      --calibration_table $(workdir)/$(name)_cali_table
      --quant_input
      --quant_output
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.89,0.5
      --model $(workdir)/$(name)_$(target)_int8_sym.bmodel

dataset:
  image_path: $(imagenet2012_val_set)
  image_label: $(imagenet2012_caffe_val_ground_truth)
  mean: [123.675, 116.28, 103.53]
  scale: [0.0171, 0.0175, 0.0174]
  resize_dims: 256
  size: 224
  trans: true
  bgr2rgb: true
 
BM1684:
  harness:
    type: topk
    args:
      - name: FP32
        bmodel: $(workdir)/$(name)_$(target)_f32.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_$(target)_int8_sym.bmodel
