---

name: openpose
gops: 98.7

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/pose_deploy.prototxt
    --model_data $(home)/pose_iter_584000.caffemodel
    --test_input $(root)/dataset/samples/reid_img.jpg
    --input_shapes [[1,3,216,384]]
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

BM1684X:
  deploy:
    - model_deploy.py  --mlir $(workdir)/transformed.mlir
        --quantize F32
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_bm1684x_f32.bmodel
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize INT8
        --calibration_table $(home)/cali_table
        --quant_input
        --quant_output
        --asymmetric
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.69,0.14
        --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel
