---

name: bert
gops: 42.87

model: $(home)/bert4torch_jit.pt

precision: true

fp_batch_sizes: [1, 8]

BM1684X:
  fp_loops:
    - build_env: [  ]
      fp_outdir_template: "{}b.fp32.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_LAYER_DTYPE_MODE=bf16
      fp_outdir_template: "{}b.fp16.compilation"
      prec: FP16

  fp_compile_options:
    python3 -m bmnetp
      --model $(model)
      --shapes [1,256]
      --net_name $(name)
      --target $(target)
      --enable_profile True
