---

name: yolov5s-5
gops: [16.588894000, 16.588894000, 16.588894000]
shapes:
  - [1, 3, 640, 640]
  - [4, 3, 640, 640]
  - [8, 3, 640, 640]
precision: true

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/yolov5s-5.0.pt
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --keep_aspect_ratio
    --mean 0.0,0.0,0.0
    --scale 0.0039216,0.0039216,0.0039216
    --pixel_format rgb
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

mlir_calibration:
  run_calibration.py $(workdir)/transformed.mlir
    --dataset $(coco2017_mlir_cali_set)
    --input_num 100
    -o $(workdir)/$(name).calitable

BM1684:
  deploy:
    - model_deploy.py  --mlir $(workdir)/transformed.mlir
        --quantize F32
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_$(target)_f32.bmodel
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize INT8
        --calibration_table $(workdir)/$(name).calitable
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.0,0.0
        --model $(workdir)/$(name)_$(target)_int8_sym.bmodel

  dataset:
    imagedir: $(coco2017_val_set)
    anno: $(coco2017_anno)/instances_val2017.json

  harness:
    type: yolo
    args:
      - name: FP32
        bmodel: $(workdir)/$(name)_$(target)_f32.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_$(target)_int8_sym.bmodel
