---

name: S-DCNet_SHA_fusepost

gops: [157.98, 631.92]

shapes:
  - [1, 3, 320, 576]
  - [4, 3, 320, 576]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/S-DCNet_SHA.pt
    --test_input $(root)/dataset/samples/crowd.jpg
    --input_shapes [$(shape_param)]
    --resize_dims 320,576
    --keep_aspect_ratio
    --test_result $(name)_top_outputs.npz
    --pixel_format rgb
    --mean 106.068794,94.819984,91.83845
    --scale 0.0039216,0.0039216,0.0039216
    --mlir $(workdir)/S-DCNet_SHA_fusepost_transformed.mlir

mlir_calibration:
  run_calibration.py $(workdir)/S-DCNet_SHA_fusepost_transformed.mlir
    --dataset $(SHA_Density_Map_cali_set)
    --input_num 100
    -o $(workdir)/$(name).cali_table

deploy:
  - model_deploy.py  --mlir $(workdir)/S-DCNet_SHA_fusepost_transformed.mlir
      --quantize F32
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_$(target)_f32.bmodel
  - model_deploy.py --mlir $(workdir)/S-DCNet_SHA_fusepost_transformed.mlir
      --quantize INT8
      --calibration_table $(workdir)/$(name).cali_table
      --quant_input
      --quant_output
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.85,0.45
      --model $(workdir)/$(name)_$(target)_int8_sym.bmodel

BM1684X:
  +deploy:
    - model_deploy.py --mlir $(workdir)/S-DCNet_SHA_fusepost_transformed.mlir
        --quantize F16
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.95,0.85
        --model $(workdir)/$(name)_bm1684x_f16.bmodel
    - model_deploy.py --mlir $(workdir)/S-DCNet_SHA_fusepost_transformed.mlir
        --quantize BF16
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.95,0.85
        --model $(workdir)/$(name)_bm1684x_bf16.bmodel
    - model_deploy.py --mlir $(workdir)/S-DCNet_SHA_fusepost_transformed.mlir
        --quantize INT8
        --asymmetric
        --calibration_table $(workdir)/$(name).cali_table
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.85,0.45
        --model $(workdir)/$(name)_$(target)_int8_asym.bmodel
