---

name: Test
on:
  push:
  pull_request:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC time 22:30
    - cron: '30 22 * * *'

jobs:
  test:
    if: github.repository == 'sophgo/model-zoo'
    name: Test Model Compiling
    runs-on: build
    environment: testing
    timeout-minutes: 1080

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false
          lfs: true

      - run: git lfs pull --exclude '' --include '*'

      - name: Set Optional Env
        if: "${{ github.event_name == 'schedule' || \
                 contains( \
                   github.event.pull_request.labels.*.name, \
                   'full_regression' \
                 ) }}"
        run: |
          echo "FULL_TEST=true" >> $GITHUB_ENV

      - run: .github/workflows/test_build.sh
